import { Movie } from '../entities/Movie';

const CaptainAmericaTheFirstAvenger = new Movie(["Chris Evans", "Hayley Atwell", "Sebastian Stan", "Tommy Lee Jones"], "3 wins & 46 nominations.", "$176,636,816", "USA", "Joe Johnston", "Action, Adventure, Sci-Fi", "Steve Rogers, a rejected military soldier transforms into Captain America after taking a dose of a 'Super-Soldier serum'. But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization.", "https://m.media-amazon.com/images/M/MV5BMTYzOTc2NzU3N15BMl5BanBnXkFtZTcwNjY3MDE3NQ@@._V1_SX300.jpg", "Paramount Pictures", ["Internet Movie Database, 6.9/10", "Rotten Tomatoes, 79%", "Metacritic, 66/100"], "22 Jul 2011", "124 min", "Captain America: The First Avenger", "http://captainamerica.marvel.com/", ['Christopher Markus (screenplay)', 'Stephen McFeely (screenplay)', 'Joe Simon (comic books)', 'Jack Kirby (comic books)'], "2011", 3);
     
const ironMan = new Movie(["Robert Downey Jr.", "Terrence Howard", "Jeff Bridges", "Gwyneth Paltrow"], "Nominated for 2 Oscars. Another 20 wins & 65 nominations.","$318,298,180", "USA", "Jon Favreau", "Action, Adventure, Sci-Fi", "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.", "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg", "Paramount Pictures", ["Internet Movie Database, 7.9/10", "Rotten Tomatoes, 93%", "Metacritic, 79/100"], "02 May 2008", "126 min", "Iron Man", "http://www.ironmanmovie.com/", ['Mark Fergus (screenplay)', 'Hawk Ostby (screenplay)', 'Art Marcum (screenplay)', 'Matt Holloway (screenplay)', 'Stan Lee (characters)', 'Don Heck (characters)', 'Larry Lieber (characters)', 'Jack Kirby (characters)'], "2008", 0);
 

const ironMan2 = new Movie (['Robert Downey Jr.', 'Gwyneth Paltrow', 'Don Cheadle', 'Scarlett Johansson'], "Nominated for 1 Oscar. Another 7 wins & 42 nominations.", "$312,057,433", "USA", "Jon Favreau", "Action, Adventure, Sci-Fi", "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father's legacy.", "https://m.media-amazon.com/images/M/MV5BMTM0MDgwNjMyMl5BMl5BanBnXkFtZTcwNTg3NzAzMw@@._V1_SX300.jpg", "Paramount Studios", ["Internet Movie Database, 7.0/10", "Rotten Tomatoes, 73%", "Metacritic, 57/100"], "07 May 2010", "124 min", "Iron Man 2", "http://www.ironmanmovie.com/",['Justin Theroux (screenplay)', 'Stan Lee (Marvel comic book)', 'Don Heck (Marvel comic book)', 'Larry Lieber (Marvel comic book)', 'Jack Kirby (Marvel comic book)'], "2010", 2);

const theIncredibleHulk = new Movie(['Edward Norton', 'Liv Tyler', 'Tim Roth', 'William Hurt'], "1 win & 8 nominations.", "$134,518,390", "USA", "Louis Leterrier", "Action, Adventure, Sci-Fi", "Bruce Banner, a scientist on the run from the U.S. Government, must find a cure for the monster he turns into, whenever he loses his temper.", "https://m.media-amazon.com/images/M/MV5BMTUyNzk3MjA1OF5BMl5BanBnXkFtZTcwMTE1Njg2MQ@@._V1_SX300.jpg", "Universal Pictures", ["Internet Movie Database, 6.8/10", "Rotten Tomatoes, 67%", "Metacritic, 61/100"], "13 Jun 2008", "112 min", "The Incredible Hulk", "http://www.incrediblehulk.com/", ['Zak Penn (screenplay)', 'Zak Penn (screen story)', 'Stan Lee (Marvel comic book)', 'Jack Kirby (Marvel comic book)'], 2008, 1);

const thor = new Movie (['Chris Hemsworth', 'Natalie Portman', 'Tom Hiddleston', 'Anthony Hopkins'], "5 wins & 30 nominations.", "$181,015,141", "USA", "Kenneth Branagh", "Action, Adventure, Fantasy", "The powerful, but arrogant god Thor, is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.", "https://m.media-amazon.com/images/M/MV5BOGE4NzU1YTAtNzA3Mi00ZTA2LTg2YmYtMDJmMThiMjlkYjg2XkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg", "Paramount Pictures", ["Internet Movie Database, 7.0/10", "Rotten Tomatoes, 77%", "Metacritic, 57/100"], "06 May 2011", "115 min", "Thor", "http://thor.marvel.com/", ['Ashley Miller (screenplay)', 'Zack Stentz (screenplay)', 'Don Payne (screenplay)', 'J. Michael Straczynski (story)', 'Mark Protosevich (story)', 'Stan Lee (comic book)', 'Larry Lieber (comic book)', 'Jack Kirby (comic book)'], "2011", 4);

const ironMan3 = new Movie (['Robert Downey Jr.', 'Gwyneth Paltrow', 'Don Cheadle', 'Guy Pearce'], "Nominated for 1 Oscar. Another 17 wins & 61 nominations.", "$408,992,272", "China, USA", "Shane Black", "Action, Adventure, Sci-Fi", "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.", "https://m.media-amazon.com/images/M/MV5BMjE5MzcyNjk1M15BMl5BanBnXkFtZTcwMjQ4MjcxOQ@@._V1_SX300.jpg", "Walt Disney Pictures", ["Internet Movie Database, 7.2/10", "Rotten Tomatoes, 79%", "Metacritic, 62/100"], "03 May 2013", "130 min", "Iron Man 3", "http://IronManMovie3.com", ['Drew Pearce (screenplay by)', 'Shane Black (screenplay by)', 'Stan Lee (based on the Marvel comic book by)', 'Don Heck (based on the Marvel comic book by)', 'Larry Lieber (based on the Marvel comic book by)', 'Jack Kirby (based on the Marvel comic book by)', 'Warren Ellis (based on the "Extremis" mini-series written by)', 'Adi Granov (based on the "Extremis" mini-series illustrated by)'], "2013", 5); 

const thorTheWarkWorld = new Movie(['Chris Hemsworth', 'Natalie Portman', 'Tom Hiddleston', 'Anthony Hopkins'], "3 wins & 21 nominations.", "$206,360,018", "USA", "Alan Taylor", "Action, Adventure", "When Dr. Jane Foster gets cursed with a powerful entity known as the Aether, Thor is heralded of the cosmic event known as the Convergence and the genocidal Dark Elves.", "https://m.media-amazon.com/images/M/MV5BMTQyNzAwOTUxOF5BMl5BanBnXkFtZTcwMTE0OTc5OQ@@._V1_SX300.jpg", "Walt Disney Pictures", ["Internet Movie Database, 7.0/10", "Rotten Tomatoes, 66%", "Metacritic, 54/100"], "08 Nov 2013", "112 min", "Thor: The Dark World", "http://www.facebook.com/ThorMovie", ['Christopher L. Yost (screenplay by)', 'Christopher Markus (screenplay by)', 'Stephen McFeely (screenplay by)', 'Don Payne (story by)', 'Robert Rodat (story by)', 'Stan Lee (based on the Marvel comics by)', 'Larry Lieber (based on the Marvel comics by)', 'Jack Kirby (based on the Marvel comics by)', 'Walter Simonson (character created by: Malekith)'], 2013, 6);

const captainAmericaTheWinterSoldier = new Movie(['Chris Evans', 'Samuel L. Jackson', 'Scarlett Johansson', 'Robert Redford'], "Nominated for 1 Oscar. Another 5 wins & 50 nominations.", "$228,636,083", "USA", "Anthony Russo, Joe Russo", "Action, Adventure, Sci-Fi", "As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier.", "https://m.media-amazon.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_SX300.jpg", "Walt Disney Pictures", ["Internet Movie Database, 7.8/10", "Rotten Tomatoes, 89%", "Metacritic, 70/100"], "04 Apr 2014", "136 min", "Captain America: The Winter Soldier", "http://marvel.com/captainamerica", ['Christopher Markus (screenplay by)', 'Stephen McFeely (screenplay by)', 'Joe Simon (based on the Marvel comics by)', 'Jack Kirby (based on the Marvel comics by)'], 2014, 7);

const guardiansOfTheGalaxy = new Movie (['Chris Pratt', 'Zoe Saldana', 'Dave Bautista', 'Vin Diesel'], "Nominated for 2 Oscars. Another 52 wins & 99 nominations.", "$270,592,504", "USA", "James Gunn", "Action, Adventure, Comedy", "A group of intergalactic criminals are forced to work together to stop a fanatical warrior from taking control of the universe.", "https://m.media-amazon.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_SX300.jpg", "Walt Disney Pictures", ["Internet Movie Database, 8.1/10", "Rotten Tomatoes, 91%", "Metacritic, 76/100"], "01 Aug 2014", "121 min", "Guardians of the Galaxy", "http://marvel.com/guardians", ['James Gunn', 'Nicole Perlman', 'Dan Abnett (based on the Marvel comics by)', 'Andy Lanning (based on the Marvel comics by)', 'Bill Mantlo (character created by: Rocket Raccoon)', 'Keith Giffen (character created by: Rocket Raccoon)', 'Jim Starlin (characters created by: Drax the Destroyer,  Gamora & Thanos)', 'Steve Englehart (character created by: Star-Lord)', 'Steve Gan (character created by: Star-Lord)', 'Steve Gerber (character created by: Howard the Duck)', 'Val Mayerik (character created by: Howard the Duck)'], 2014, 8);

const guardiansOfTheGalaxyVol2 = new Movie(['Chris Pratt', 'Zoe Saldana', 'Dave Bautista', 'Vin Diesel'], "Nominated for 1 Oscar. Another 12 wins & 42 nominations.", "$389,804,217", "USA", "James Gunn", "Action, Adventure, Comedy", "The Guardians must fight to keep their newfound family together as they unravel the mystery of Peter Quill's true parentage.", "https://m.media-amazon.com/images/M/MV5BMTg2MzI1MTg3OF5BMl5BanBnXkFtZTgwNTU3NDA2MTI@._V1_SX300.jpg", "Walt Disney Pictures", ["Internet Movie Database, 7.7/10", "Rotten Tomatoes, 83%", "Metacritic, 67/100"], "05 May 2017", "136 min", "Guardians of the Galaxy Vol. 2", "https://marvel.com/guardians", ['James Gunn', 'Dan Abnett (based on the Marvel comics by)', 'Andy Lanning (based on the Marvel comics by)', 'Steve Englehart (Star-Lord created by)', 'Steve Gan (Star-Lord created by)', 'Jim Starlin (Gamora and Drax created by)', 'Stan Lee (Groot created by)', 'Larry Lieber (Groot created by)', 'Jack Kirby (Groot created by)', 'Bill Mantlo (Rocket Raccoon created by)', 'Keith Giffen (Rocket Raccoon created by)', 'Steve Gerber (Howard the Duck created by)', 'Val Mayerik (Howard the Duck created by)'], 2017, 11);

const avengersAgeOfUltron = new Movie(['Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo', 'Chris Evans'], "7 wins & 45 nominations.", "$429,113,729", "USA,", "Joss Whedon", "Action, Adventure, Sci-Fi", "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.", "https://images-na.ssl-images-amazon.com/images/I/719S7I-%2ByBL._SY679_.jpg", "Walt Disney Pictures",  ["Internet Movie Database, 7.4/10", "Rotten Tomatoes, 75%", "Metacritic, 66/100"], "01 May 2015", "141 min", "Avengers: Age of Ultron", "http://marvel.com/avengers", ['Joss Whedon', 'Stan Lee (based on the Marvel comics by)', 'Jack Kirby (based on the Marvel comics by)', 'Joe Simon (character created by: Captain America)', 'Jack Kirby (character created by: Captain America)', 'Jim Starlin (character created by: Thanos)'], 2015, 9);

const antMan = new Movie(['Paul Rudd', 'Michael Douglas', 'Evangeline Lilly', 'Corey Stoll'], "Nominated for 1 BAFTA Film Award. Another 3 wins & 32 nominations.", "$138,002,223", "USA", "Peyton Reed", "Action, Adventure, Comedy", "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "https://m.media-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_SX300.jpg", "Disney/Marvel", ["Internet Movie Database, 7.3/10", "Rotten Tomatoes, 82%", "Metacritic, 64/100"], "17 Jul 2015", "117 min", "Ant-Man", "http://www.facebook.com/antman", ['Edgar Wright (screenplay by)', 'Joe Cornish (screenplay by)', 'Adam McKay (screenplay by)', 'Paul Rudd (screenplay by)', 'Edgar Wright (story by)', 'Joe Cornish (story by)', 'Stan Lee (based on the Marvel comics by)', 'Larry Lieber (based on the Marvel comics by)', 'Jack Kirby (based on the Marvel comics by)'], 2015, 10);

const captainAmericaCivilWar = new Movie( ['Chris Evans', 'Robert Downey Jr.', 'Scarlett Johansson', 'Sebastian Stan'], "16 wins & 65 nominations.", "$408,080,554",  "USA, Germany", "Anthony Russo, Joe Russo", "Action, Adventure, Sci-Fi", "Political involvement in the Avengers' activities causes a rift between Captain America and Iron Man.", "https://m.media-amazon.com/images/M/MV5BMjQ0MTgyNjAxMV5BMl5BanBnXkFtZTgwNjUzMDkyODE@._V1_SX300.jpg", "Walt Disney Pictures", ["Internet Movie Database, 7.8/10", "Rotten Tomatoes, 91%", "Metacritic, 75/100"], "06 May 2016", "147 min", "Captain America: Civil War", "http://marvel.com/captainamerica#/home", ['Christopher Markus (screenplay by)', 'Stephen McFeely (screenplay by)', 'Joe Simon (based on the Marvel comics by)', 'Jack Kirby (based on the Marvel comics by)'], 2016, 12);

const blackPanther = new Movie(['Chadwick Boseman', 'Michael B. Jordan', 'Lupita Nyong"o', 'Danai Gurira'], "14 nominations.", "$501,105,037", "USA, South Africa, South Korea, Australia", "Ryan Coogler", "Action, Adventure, Sci-Fi", "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.", "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg", "Marvel Studios", ["Internet Movie Database, 7.4/10", "Rotten Tomatoes, 97%", "Metacritic, 88/100"], "16 Feb 2018"
    ,"134 min", "Black Panther", "https://www.marvel.com/blackpanther", ['Ryan Coogler', 'Joe Robert Cole', 'Stan Lee (based on the Marvel comics by)', 'Jack Kirby (based on the Marvel Comics by)'], 2018, 16);

const doctorStrange = new Movie(['Benedict Cumberbatch', 'Chiwetel Ejiofor', 'Rachel McAdams', 'Benedict Wong'], "Nominated for 1 Oscar. Another 20 wins & 64 nominations.", "$232,630,718", "USA", "Scott Derrickson", "Action, Adventure, Fantasy", "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.", "https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_SX300.jpg", "Walt Disney Pictures", ["Internet Movie Database, 7.5/10", "Rotten Tomatoes, 89%", "Metacritic, 72/100"], "04 Nov 2016", "115 min", "Doctor Strange", "http://marvel.com/doctorstrange", ['Jon Spaihts', 'Scott Derrickson', 'C. Robert Cargill', 'Stan Lee (based on the Marvel comics by)', 'Steve Ditko (based on the Marvel comics by)'], 2016, 13);
 
const spiderManHomecoming = new Movie(['Tom Holland', 'Michael Keaton', 'Robert Downey Jr.', 'Marisa Tomei'], "4 wins & 9 nominations.", "$334,166,825", "USA", "Jon Watts", "Action, Adventure, Sci-Fi", "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.", "https://m.media-amazon.com/images/M/MV5BNTk4ODQ1MzgzNl5BMl5BanBnXkFtZTgwMTMyMzM4MTI@._V1_SX300.jpg", "Sony Pictures", ["Internet Movie Database, 7.5/10", "Rotten Tomatoes, 92%", "Metacritic, 73/100"], "07 Jul 2017", "133 min", "Spider-Man: Homecoming", "http://www.sonypictures.com/movies/spidermanhomecoming/", ['Jonathan Goldstein (screenplay by)', 'John Francis Daley (screenplay by)', 'Jon Watts (screenplay by)', 'Christopher Ford (screenplay by)', 'Chris McKenna (screenplay by)', 'Erik Sommers (screenplay by)', 'Jonathan Goldstein (screen story by)', 'John Francis Daley (screen story by)', 'Stan Lee (based on the Marvel comic book by)', 'Steve Ditko (based on the Marvel comic book by)', 'Joe Simon (Captain America created by)', 'Jack Kirby (Captain America created by)'], 2017, 14);

const thorRagnarok = new Movie(['Chris Hemsworth', 'Tom Hiddleston', 'Cate Blanchett', 'Idris Elba'], "5 wins & 30 nominations.", "$314,971,245", "USA, Australia", "Taika Waititi", "Action, Adventure, Comedy", "Thor is imprisoned on the planet Sakaar, and must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.", "https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_SX300.jpg", "Walt Disney Pictures", ["Internet Movie Database, 7.9/10", "Rotten Tomatoes, 92%", "Metacritic, 74/100"], "03 Nov 2017",  "130 min", "Thor: Ragnarok",  "http://movies.disney.com/thor-ragnarok", ['Eric Pearson', 'Craig Kyle', 'Christopher L. Yost', 'Stan Lee (based on the Marvel comics by)', 'Larry Lieber (based on the Marvel comics by)', 'Jack Kirby (based on the Marvel comics by)'], 2017, 15);

const antManAndTheWasp = new Movie(['Paul Rudd', 'Evangeline Lilly', 'Michael Peña', 'Walton Goggins'], "N/A", "N/A", "USA", "Peyton Reed", "Action, Adventure, Sci-Fi", "As Scott Lang balances being both a Super Hero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.", "https://m.media-amazon.com/images/M/MV5BYjcyYTk0N2YtMzc4ZC00Y2E0LWFkNDgtNjE1MzZmMGE1YjY1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", "Walt Disney Pictures", ["Internet Movie Database, 7.4/10", "Rotten Tomatoes, 89%", "Metacritic, 70/100"], "06 Jul 2018", "118 min", "Ant-Man and the Wasp", "https://marvel.com/antman", ['Chris McKenna', 'Erik Sommers', 'Paul Rudd', 'Andrew Barrer', 'Gabriel Ferrari', 'Stan Lee (based on the Marvel Comics by)', 'Larry Lieber (based on the Marvel Comics by)', 'Jack Kirby (based on the Marvel Comics by)'], 2018, 17);

const avengersInfinityWar = new Movie(['Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo', 'Chris Evans'], "N/A", '$678,815,482', "USA", "Anthony Russo, Joe Russo", "Action, Adventure, Drama", "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.", "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg", "Walt Disney Pictures", ["Internet Movie Database, 8.6/10", "Rotten Tomatoes, 83%", "Metacritic, 68/100"], "27 Apr 2018", "149 min", "Avengers: Infinity War", "http://marvel.com/movies/movie/223/avengers_infinity_war"
, ['Christopher Markus (screenplay by)', 'Stephen McFeely (screenplay by)', 'Stan Lee (based on the Marvel comics by)', 'Jack Kirby (based on the Marvel comics by)', 'Joe Simon (Captain America created by)', 'Jack Kirby (Captain America created by)', 'Steve Englehart (Star-Lord created by)', 'Steve Gan (Star-Lord created by)', 'Bill Mantlo (Rocket Raccoon created by)', 'Keith Giffen (Rocket Raccoon created by)', 'Jim Starlin (Thanos,  Gamora and Drax created by)', 'Stan Lee (Groot created by)', 'Larry Lieber (Groot created by)', 'Jack Kirby (Groot created by)', 'Steve Englehart (Mantis created by)', 'Don Heck (Mantis created by)'], 2018, 18);


export const marvelMovies = [];

marvelMovies.push(ironMan, theIncredibleHulk, ironMan2, CaptainAmericaTheFirstAvenger, thor, ironMan3, thorTheWarkWorld  , captainAmericaTheWinterSoldier, guardiansOfTheGalaxy, avengersAgeOfUltron, antMan, captainAmericaCivilWar, doctorStrange, guardiansOfTheGalaxyVol2, spiderManHomecoming, thorRagnarok, blackPanther, antManAndTheWasp,avengersInfinityWar);  

